<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="Avalonia.Skia" Version="12.1.1" />
    <PackageReference Include="AvaloniaDialogs" Version="3.7.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Silk.NET.OpenGL" Version="2.23.0" />
    <PackageReference Include="Svg.Skia" Version="5.1.1" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Resources\Icons.axaml" />
    <AvaloniaResource Include="Resources\googlefonts.txt" />
    <AvaloniaResource Include="..\Elmanager.WinForms\Resources\lgrs.json" Link="Resources\lgrs.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Elmanager.Core\Elmanager.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Elmanager.SLE.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
