<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <RootNamespace>Elmanager</RootNamespace>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Configurations>Debug;Release;WineRelease</Configurations>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)'=='WineRelease'">
        <Optimize>True</Optimize>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)'=='WineRelease'">
        <DefineConstants>$(DefineConstants);WINE</DefineConstants>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="NetTopologySuite" Version="2.6.0" />
        <PackageReference Include="Silk.NET.OpenGL" Version="2.23.0" />
        <PackageReference Include="SkiaSharp" Version="3.119.4" />
    </ItemGroup>
</Project>
