using System.Windows.Forms;
using Elmanager.LevelEditor.Input;

namespace Elmanager.LevelEditor.Tools.Platform;

internal static class InputAdapter
{
    internal static EditorMouseButton ToEditorMouseButton(MouseButtons button) => button switch
    {
        MouseButtons.Left => EditorMouseButton.Left,
        MouseButtons.Right => EditorMouseButton.Right,
        MouseButtons.Middle => EditorMouseButton.Middle,
        _ => EditorMouseButton.None,
    };

    internal static EditorMouseEventArgs ToEditorMouseEventArgs(MouseEventArgs e) =>
        new(ToEditorMouseButton(e.Button));

    internal static EditorKey ToEditorKey(Keys keyCode) => keyCode switch
    {
        Keys.Up => EditorKey.Up,
        Keys.Down => EditorKey.Down,
        Keys.Left => EditorKey.Left,
        Keys.Right => EditorKey.Right,
        Keys.Space => EditorKey.Space,
        Keys.Enter => EditorKey.Enter,
        Keys.Escape => EditorKey.Escape,
        Keys.Tab => EditorKey.Tab,
        Keys.Back => EditorKey.Back,
        Keys.Insert => EditorKey.Insert,
        Keys.Delete => EditorKey.Delete,
        Keys.Home => EditorKey.Home,
        Keys.End => EditorKey.End,
        Keys.PageUp => EditorKey.PageUp,
        Keys.PageDown => EditorKey.PageDown,
        Keys.LShiftKey => EditorKey.LShiftKey,
        Keys.RShiftKey => EditorKey.RShiftKey,
        Keys.LControlKey => EditorKey.LControlKey,
        Keys.RControlKey => EditorKey.RControlKey,
        Keys.LMenu => EditorKey.LMenu,
        Keys.RMenu => EditorKey.RMenu,
        Keys.A => EditorKey.A,
        Keys.B => EditorKey.B,
        Keys.C => EditorKey.C,
        Keys.D => EditorKey.D,
        Keys.E => EditorKey.E,
        Keys.F => EditorKey.F,
        Keys.G => EditorKey.G,
        Keys.H => EditorKey.H,
        Keys.I => EditorKey.I,
        Keys.J => EditorKey.J,
        Keys.K => EditorKey.K,
        Keys.L => EditorKey.L,
        Keys.M => EditorKey.M,
        Keys.N => EditorKey.N,
        Keys.O => EditorKey.O,
        Keys.P => EditorKey.P,
        Keys.Q => EditorKey.Q,
        Keys.R => EditorKey.R,
        Keys.S => EditorKey.S,
        Keys.T => EditorKey.T,
        Keys.U => EditorKey.U,
        Keys.V => EditorKey.V,
        Keys.W => EditorKey.W,
        Keys.X => EditorKey.X,
        Keys.Y => EditorKey.Y,
        Keys.Z => EditorKey.Z,
        Keys.D0 => EditorKey.D0,
        Keys.D1 => EditorKey.D1,
        Keys.D2 => EditorKey.D2,
        Keys.D3 => EditorKey.D3,
        Keys.D4 => EditorKey.D4,
        Keys.D5 => EditorKey.D5,
        Keys.D6 => EditorKey.D6,
        Keys.D7 => EditorKey.D7,
        Keys.D8 => EditorKey.D8,
        Keys.D9 => EditorKey.D9,
        Keys.F1 => EditorKey.F1,
        Keys.F2 => EditorKey.F2,
        Keys.F3 => EditorKey.F3,
        Keys.F4 => EditorKey.F4,
        Keys.F5 => EditorKey.F5,
        Keys.F6 => EditorKey.F6,
        Keys.F7 => EditorKey.F7,
        Keys.F8 => EditorKey.F8,
        Keys.F9 => EditorKey.F9,
        Keys.F10 => EditorKey.F10,
        Keys.F11 => EditorKey.F11,
        Keys.F12 => EditorKey.F12,
        Keys.NumPad0 => EditorKey.NumPad0,
        Keys.NumPad1 => EditorKey.NumPad1,
        Keys.NumPad2 => EditorKey.NumPad2,
        Keys.NumPad3 => EditorKey.NumPad3,
        Keys.NumPad4 => EditorKey.NumPad4,
        Keys.NumPad5 => EditorKey.NumPad5,
        Keys.NumPad6 => EditorKey.NumPad6,
        Keys.NumPad7 => EditorKey.NumPad7,
        Keys.NumPad8 => EditorKey.NumPad8,
        Keys.NumPad9 => EditorKey.NumPad9,
        Keys.Add => EditorKey.Add,
        Keys.Subtract => EditorKey.Subtract,
        Keys.Multiply => EditorKey.Multiply,
        Keys.Divide => EditorKey.Divide,
        Keys.Decimal => EditorKey.Decimal,
        Keys.Oemplus => EditorKey.OemPlus,
        Keys.OemMinus => EditorKey.OemMinus,
        Keys.Oemcomma => EditorKey.OemComma,
        Keys.OemPeriod => EditorKey.OemPeriod,
        Keys.Oem1 => EditorKey.Oem1,
        Keys.Oem2 => EditorKey.Oem2,
        Keys.Oem3 => EditorKey.Oem3,
        Keys.Oem4 => EditorKey.Oem4,
        Keys.Oem5 => EditorKey.Oem5,
        Keys.Oem6 => EditorKey.Oem6,
        Keys.Oem7 => EditorKey.Oem7,
        Keys.Oem8 => EditorKey.Oem8,
        Keys.OemBackslash => EditorKey.OemBackslash,
        Keys.PrintScreen => EditorKey.PrintScreen,
        Keys.Scroll => EditorKey.Scroll,
        Keys.Pause => EditorKey.Pause,
        Keys.Capital => EditorKey.Capital,
        Keys.NumLock => EditorKey.NumLock,
        _ => EditorKey.None,
    };

    internal static EditorKeyEventArgs ToEditorKeyEventArgs(KeyEventArgs e) =>
        new(ToEditorKey(e.KeyCode));
}
