using System.Windows.Forms;
using System.Windows.Input;
using Elmanager.LevelEditor.Input;

namespace Elmanager.LevelEditor.Tools.Platform;

internal class WinFormsKeyboardState : IKeyboardState
{
    public bool IsKeyDown(ModifierKey key) => key switch
    {
        ModifierKey.LeftCtrl => Keyboard.IsKeyDown(Key.LeftCtrl),
        ModifierKey.LeftShift => Keyboard.IsKeyDown(Key.LeftShift),
        ModifierKey.LeftAlt => Keyboard.IsKeyDown(Key.LeftAlt),
        _ => false,
    };

    public bool IsKeyDown(EditorKey key) => key switch
    {
        EditorKey.None => false,
        EditorKey.A => Keyboard.IsKeyDown(Key.A),
        EditorKey.B => Keyboard.IsKeyDown(Key.B),
        EditorKey.C => Keyboard.IsKeyDown(Key.C),
        EditorKey.D => Keyboard.IsKeyDown(Key.D),
        EditorKey.E => Keyboard.IsKeyDown(Key.E),
        EditorKey.F => Keyboard.IsKeyDown(Key.F),
        EditorKey.G => Keyboard.IsKeyDown(Key.G),
        EditorKey.H => Keyboard.IsKeyDown(Key.H),
        EditorKey.I => Keyboard.IsKeyDown(Key.I),
        EditorKey.J => Keyboard.IsKeyDown(Key.J),
        EditorKey.K => Keyboard.IsKeyDown(Key.K),
        EditorKey.L => Keyboard.IsKeyDown(Key.L),
        EditorKey.M => Keyboard.IsKeyDown(Key.M),
        EditorKey.N => Keyboard.IsKeyDown(Key.N),
        EditorKey.O => Keyboard.IsKeyDown(Key.O),
        EditorKey.P => Keyboard.IsKeyDown(Key.P),
        EditorKey.Q => Keyboard.IsKeyDown(Key.Q),
        EditorKey.R => Keyboard.IsKeyDown(Key.R),
        EditorKey.S => Keyboard.IsKeyDown(Key.S),
        EditorKey.T => Keyboard.IsKeyDown(Key.T),
        EditorKey.U => Keyboard.IsKeyDown(Key.U),
        EditorKey.V => Keyboard.IsKeyDown(Key.V),
        EditorKey.W => Keyboard.IsKeyDown(Key.W),
        EditorKey.X => Keyboard.IsKeyDown(Key.X),
        EditorKey.Y => Keyboard.IsKeyDown(Key.Y),
        EditorKey.Z => Keyboard.IsKeyDown(Key.Z),
        EditorKey.D0 => Keyboard.IsKeyDown(Key.D0),
        EditorKey.D1 => Keyboard.IsKeyDown(Key.D1),
        EditorKey.D2 => Keyboard.IsKeyDown(Key.D2),
        EditorKey.D3 => Keyboard.IsKeyDown(Key.D3),
        EditorKey.D4 => Keyboard.IsKeyDown(Key.D4),
        EditorKey.D5 => Keyboard.IsKeyDown(Key.D5),
        EditorKey.D6 => Keyboard.IsKeyDown(Key.D6),
        EditorKey.D7 => Keyboard.IsKeyDown(Key.D7),
        EditorKey.D8 => Keyboard.IsKeyDown(Key.D8),
        EditorKey.D9 => Keyboard.IsKeyDown(Key.D9),
        EditorKey.F1 => Keyboard.IsKeyDown(Key.F1),
        EditorKey.F2 => Keyboard.IsKeyDown(Key.F2),
        EditorKey.F3 => Keyboard.IsKeyDown(Key.F3),
        EditorKey.F4 => Keyboard.IsKeyDown(Key.F4),
        EditorKey.F5 => Keyboard.IsKeyDown(Key.F5),
        EditorKey.F6 => Keyboard.IsKeyDown(Key.F6),
        EditorKey.F7 => Keyboard.IsKeyDown(Key.F7),
        EditorKey.F8 => Keyboard.IsKeyDown(Key.F8),
        EditorKey.F9 => Keyboard.IsKeyDown(Key.F9),
        EditorKey.F10 => Keyboard.IsKeyDown(Key.F10),
        EditorKey.F11 => Keyboard.IsKeyDown(Key.F11),
        EditorKey.F12 => Keyboard.IsKeyDown(Key.F12),
        EditorKey.Up => Keyboard.IsKeyDown(Key.Up),
        EditorKey.Down => Keyboard.IsKeyDown(Key.Down),
        EditorKey.Left => Keyboard.IsKeyDown(Key.Left),
        EditorKey.Right => Keyboard.IsKeyDown(Key.Right),
        EditorKey.Home => Keyboard.IsKeyDown(Key.Home),
        EditorKey.End => Keyboard.IsKeyDown(Key.End),
        EditorKey.PageUp => Keyboard.IsKeyDown(Key.PageUp),
        EditorKey.PageDown => Keyboard.IsKeyDown(Key.PageDown),
        EditorKey.Insert => Keyboard.IsKeyDown(Key.Insert),
        EditorKey.Delete => Keyboard.IsKeyDown(Key.Delete),
        EditorKey.Space => Keyboard.IsKeyDown(Key.Space),
        EditorKey.Enter => Keyboard.IsKeyDown(Key.Enter),
        EditorKey.Escape => Keyboard.IsKeyDown(Key.Escape),
        EditorKey.Tab => Keyboard.IsKeyDown(Key.Tab),
        EditorKey.Back => Keyboard.IsKeyDown(Key.Back),
        EditorKey.LShiftKey => GetAsyncKeyState(Keys.LShiftKey),
        EditorKey.RShiftKey => GetAsyncKeyState(Keys.RShiftKey),
        EditorKey.LControlKey => GetAsyncKeyState(Keys.LControlKey),
        EditorKey.RControlKey => GetAsyncKeyState(Keys.RControlKey),
        EditorKey.LMenu => GetAsyncKeyState(Keys.LMenu),
        EditorKey.RMenu => GetAsyncKeyState(Keys.RMenu),
        EditorKey.NumPad0 => Keyboard.IsKeyDown(Key.NumPad0),
        EditorKey.NumPad1 => Keyboard.IsKeyDown(Key.NumPad1),
        EditorKey.NumPad2 => Keyboard.IsKeyDown(Key.NumPad2),
        EditorKey.NumPad3 => Keyboard.IsKeyDown(Key.NumPad3),
        EditorKey.NumPad4 => Keyboard.IsKeyDown(Key.NumPad4),
        EditorKey.NumPad5 => Keyboard.IsKeyDown(Key.NumPad5),
        EditorKey.NumPad6 => Keyboard.IsKeyDown(Key.NumPad6),
        EditorKey.NumPad7 => Keyboard.IsKeyDown(Key.NumPad7),
        EditorKey.NumPad8 => Keyboard.IsKeyDown(Key.NumPad8),
        EditorKey.NumPad9 => Keyboard.IsKeyDown(Key.NumPad9),
        EditorKey.Add => Keyboard.IsKeyDown(Key.Add),
        EditorKey.Subtract => Keyboard.IsKeyDown(Key.Subtract),
        EditorKey.Multiply => Keyboard.IsKeyDown(Key.Multiply),
        EditorKey.Divide => Keyboard.IsKeyDown(Key.Divide),
        EditorKey.Decimal => Keyboard.IsKeyDown(Key.Decimal),
        EditorKey.OemPlus => Keyboard.IsKeyDown(Key.OemPlus),
        EditorKey.OemMinus => Keyboard.IsKeyDown(Key.OemMinus),
        EditorKey.OemComma => Keyboard.IsKeyDown(Key.OemComma),
        EditorKey.OemPeriod => Keyboard.IsKeyDown(Key.OemPeriod),
        EditorKey.Oem1 => Keyboard.IsKeyDown(Key.Oem1),
        EditorKey.Oem2 => Keyboard.IsKeyDown(Key.Oem2),
        EditorKey.Oem3 => Keyboard.IsKeyDown(Key.OemTilde),
        EditorKey.Oem4 => Keyboard.IsKeyDown(Key.OemOpenBrackets),
        EditorKey.Oem5 => Keyboard.IsKeyDown(Key.OemPipe),
        EditorKey.Oem6 => Keyboard.IsKeyDown(Key.OemCloseBrackets),
        EditorKey.Oem7 => Keyboard.IsKeyDown(Key.OemQuotes),
        EditorKey.Oem8 => Keyboard.IsKeyDown(Key.DeadCharProcessed),
        EditorKey.OemBackslash => Keyboard.IsKeyDown(Key.OemBackslash),
        EditorKey.PrintScreen => Keyboard.IsKeyDown(Key.PrintScreen),
        EditorKey.Scroll => Keyboard.IsKeyDown(Key.Scroll),
        EditorKey.Pause => Keyboard.IsKeyDown(Key.Pause),
        EditorKey.Capital => Keyboard.IsKeyDown(Key.Capital),
        EditorKey.NumLock => Keyboard.IsKeyDown(Key.NumLock),
        _ => false,
    };

    // Use GetAsyncKeyState for left/right-distinguishing keys that WPF Keyboard doesn't expose individually.
    private static bool GetAsyncKeyState(Keys key) =>
        Elmanager.IO.KeyboardUtils.IsKeyDown(key);
}
